# BiteBack

@baseURL = https://biteback.pl/api/
@userID = 69228ab94492c74f4bbd50d2

###
# group: user
# @name user/:userID
GET {{baseURL}}user/{{userID}}

###
# group: user
# @name user/register
POST {{baseURL}}user/register
Content-Type: application/json

{
  "username": "User",
  "email": "user@mail.com",
  "password": "Password123#"
}

> {%
    client.test("Should return 409 Conflict", () => {
        client.assert(response.status === 409)
    })
%}

###
# group: user
# @name user/login
POST {{baseURL}}user/login
Content-Type: application/json

{
  "email": "user@mail.com",
  "password": "Password123#"
}

> {%
    const token = response.body

    client.global.set("token", token)
%}

###
# group: user
# @name user/auth
# @test name=Auth
GET {{baseURL}}user/auth
Authorization: Bearer {{token}}

###
# group: user
# @name user/:userID
PATCH {{baseURL}}user/lang/{{userID}}
Content-Type: application/json

{
  "params": [
    {
      "name": "lang",
      "value": "en"
    }
  ]
}

###
# group: fridge
# @name fridge/:userID
GET {{baseURL}}fridge/{{userID}}

###
# group: fridge
# @name fridge/:userID
POST {{baseURL}}fridge/{{userID}}
Content-Type: application/json

[
  {
    "name": "KAJZERKA 2,34C",
    "amount": 50,
    "unit": "g",
    "category": "other",
    "iconUrl": "",
    "expDate": "2025-11-22T07:17:49.839Z"
  }
]

###
# group: fridge
# @name fridge/:userID
PATCH {{baseURL}}fridge/{{userID}}
Content-Type: application/json

{
  "id": "69221307a872116e873de371",
  "params": [
    {
      "name": "name",
      "value": "KAJZERKA"
    },
    {
      "name": "amount",
      "value": 50
    },
    {
      "name": "unit",
      "value": "g"
    },
    {
      "name": "category",
      "value": "other"
    },
    {
      "name": "iconUrl",
      "value": ""
    },
    {
      "name": "expDate",
      "value": "2025-11-22T07:17:49.839Z"
    }
  ]
}

###
# group: fridge
# @name fridge/:userID
DELETE {{baseURL}}fridge/{{userID}}

###
# group: ai
# @name ai/scan
POST {{baseURL}}ai/scan
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="test.png"
Content-Type: image/png

< ./test.png
--WebAppBoundary